import {
  card1,
  card2,
  card3,
  card4,
  card5,
  latest1,
  latest2,
  latest3,
  latest4,
  new1,
  new2,
  new3,
  new4,
} from "../assets/img/img";

export const Products = [
  {
    img: card1,
    titlle: "All Natural Makeup Beauty Cosmetics",
    price: 11.90,
    id: 1,
  },
  {
    img: card2,
    titlle: "On Trend Makeup and Beauty Cosmetics",
    price: 11.90,
    id: 2,
  },
  {
    img: card3,
    titlle: "The Cosmetics and Beauty brand Shoppe",
    price: 21.51,
    id: 3,
  },
  {
    img: card4,
    titlle: "orginal Age Defying Cosmetics Makeup",
    price: 11.90,
    id: 4,
  },
  {
    img: card5,
    titlle: "orginal Age Defying Cosmetics Trend",
    price: 11.90,
    id: 5,
  },
  {
    img: new1,
    titlle: "All Natural Makeup Beauty Cosmetics",
    price: 11.90,
    category: "new",
    id: 6,
  },
  {
    img: new2,
    titlle: "On Trend Makeup and Beauty Cosmetics",
    price: 11.90,
    category: "new",
    id: 7,
  },
  {
    img: new3,
    titlle: "The Cosmetics and Beauty brand Shoppe",
    price: 21.51,
    category: "new",
    id: 9,
  },
  {
    img: new4,
    titlle: "orginal Age Defying Cosmetics Makeup",
    price: 11.90,
    category: "new",
    id: 10,
  },
  {
    img: new1,
    titlle: "orginal Age Defying Cosmetics Makeup",
    price: "$11.90",
    category: "new",
    id: 11,
  },
];

export const ImageGallery = [
  {
    img: latest1,
    text1: "Fashion",
    titlle: "This is first Post For Blog",
    category: "latest",
    id: 1,
  },
  {
    img: latest2,
    text1: "Fashion",
    titlle: "This is Second Post For Blog",
    category: "latest",
    id: 2,
  },
  {
    img: latest3,
    text1: "Fashion",
    titlle: "This is Third Post For Blog",
    category: "latest",
    id: 3,
  },
  {
    img: latest4,
    text1: "Fashion",
    titlle: "This is fouth Post For Blog",
    category: "latest",
    id: 4,
  },
  {
    img: card1,
    text1: "Fashion",
    titlle: "This is fouth Post For Blog",
    category: "latest",
    id: 5,
  },
];
